version: "3"

services:
  nginx:
    # Note : Only nginx:alpine supports bcrypt.
    # If you don't need to use bcrypt, you can use a different tag.
    # Ref. https://github.com/nginxinc/docker-nginx/issues/29
    image: "nginx:alpine"
    ports:
      - 443:443
    depends_on:
      - registry
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./certs:/etc/nginx/certs:ro
      - ./test-htpasswd:/etc/nginx/htpasswd:ro

  registry:
    build: .
    volumes:
      - ./data:/var/lib/registry
    ports:
      - 5000:5000
